spring.application.name=next-solution
server.port=88

spring.ai.vectorstore.qdrant.host=${SPRING_AI_VECTORSTORE_QDRANT_HOST:localhost}
spring.ai.vectorstore.qdrant.port=${SPRING_AI_VECTORSTORE_QDRANT_PORT:6334}
spring.ai.vectorstore.qdrant.use-tls=${SPRING_AI_VECTORSTORE_QDRANT_USE_TLS:false}
spring.ai.vectorstore.qdrant.collection-name=${SPRING_AI_VECTORSTORE_QDRANT_COLLECTION_NAME:stop_list_collection}
app.qdrant.collection-name=${SPRING_AI_VECTORSTORE_QDRANT_COLLECTION_NAME:stop_list_collection}
app.qdrant.vector-size=768
app.qdrant.distance=Cosine